stages:
  - build
  - test
  # TODO deploy stage

image: edbizarro/gitlab-ci-pipeline-php:7.4

services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_DATABASE: food_service_db
  MYSQL_USER: homestead
  MYSQL_PASSWORD:  secret
  DB_HOST: mysql

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key:
    files:
      - composer.lock
  paths:
    - vendor/

build:
  stage: build
  only:
    - merge_requests
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - cp .env.testing .env
    - php artisan key:generate
    - php artisan config:cache
    - php artisan migrate:fresh
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 7 days
    when: always

test:
  stage: test
  only:
    - merge_requests
  script:
    - vendor/bin/phpunit --coverage-text --colors=never
